name: Document
on:
  push:
    branches:
      - master
      - update-documents-with-scheduled-run
  pull_request:
  schedule:
    - cron: 0 0 * * *
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mroonga/mroonga
          path: mroonga
          submodules: recursive
      - name: Prepare ccache
        run: |
          echo "CCACHE_DIR=${PWD}/ccache" >> ${GITHUB_ENV}
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ccache
          key: document-linux-ccache-${{ hashFiles('lib/**', 'src/**', 'plugins/**', 'include/**') }}
          restore-keys: document-linux-ccache-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Install dependencies
        run: |
          mroonga/setup.sh
          pip install -r mroonga/doc/requirements.txt
          (cd mroonga/doc && bundle install)
      - name: Build document
        run: |
          ccache --show-stats --verbose --version || :
          cmake \
            -S mroonga \
            -B /tmp/mroonga.build --preset=doc \
            -DMYSQL_SOURCE_DIR=/tmp/mariadb-${mariadb-version} \
            -DMYSQL_BUILD_DIR=/tmp/mariadb-${mariadb-version}.build \
            -DMYSQL_CONFIG=/usr/bin/mariadb_config
          rm -rf dev/docs dev/ja/docs
          mkdir -p dev/ja
          rake -C mroonga release:document:update BUILD_DIR=/tmp/mroonga.build MROONGA_ORG_DIR=../dev
          ccache --show-stats --verbose --version || :
          git add -N dev
          if ! git diff --exit-code dev; then
            echo "GIT_DIFF=yes" >> ${GITHUB_ENV}
          fi
      - name: Git push
        if: env.GIT_DIFF == 'yes' && github.event_name == 'schedule'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dev/docs dev/ja/docs
          git commit -m "Update the document"
          git push origin HEAD:master
